### PR TITLE
Include threshold matrices from ImageMagick

### LINKED ISSUE #22: Include all ordered dithering methods available in ImageMagick
A summary of threshold maps in ImageMagick can be found [here](https://imagemagick.org/script/command-line-options.php#ordered-dither), the threshold maps and their references [in this XML file](https://imagemagick.org/source/thresholds.xml).

### PR DESCRIPTION
**Pull request by adrhill**
Closes #22.

I decided against adding `h16x16o` "Halftone 16x16 (orthogonal)", as it looks really bad.

Do we need to include the [ImageMagick License](https://imagemagick.org/script/license.php)? This PR doesn't copy any code, just threshold matrices.
> It requires you to:
> * include a copy of the license in any redistribution you may make that includes ImageMagick software;

I'm also open for name changes to the functions!

### CODE REVIEW

**Review by johnnychen94 — COMMENTED** [review]
> Do we need to include the ImageMagick License? This PR doesn't copy any code, just threshold matrices.
>
> > It requires you to:
> > include a copy of the license in any redistribution you may make that includes ImageMagick software;

I'm not very sure of it. One similar case I noticed is [`Interpolations.Lanczos4OpenCV`](https://github.com/JuliaMath/Interpolations.jl/blob/617a6666e76328283e8d32f39202542bf69de295/src/lanczos/lanczos.jl#L96-L102) where there is no license (Apache) copied.

cc: @timholy @mkitti

---

For the API and names, I'm a bit worried about the discoverability and scales. But maybe it won't be an issue as long as we have a good example gallery.

**Comment by adrhill** [comment]
> For the API and names, I'm a bit worried about the discoverability and scales. But maybe it won't be an issue as long as we have a good example gallery.

The original names in ImageMagic can be seen [here](https://imagemagick.org/script/command-line-options.php#ordered-dither), e.g. `c5x5`, `h4x4a`, `h4x4o`.  
I thought about adding a submodule to allow for `ImageMagick.o4x4()` but I was afraid of conflicts with ImageMagick.jl. So for now I just prefixed `IM_`.

An alternative would be to call ImageMagick's `h4x4o` through something like `HalftoneOrthogonal(; size::Int = 4)`. However, the only other allowed sizes would be `size = 6` and `8` and we'd have to throw an error for other arguments.

**Comment by mkitti** [comment]
> I'm not very sure of it. One similar case I noticed is [`Interpolations.Lanczos4OpenCV`](https://github.com/JuliaMath/Interpolations.jl/blob/617a6666e76328283e8d32f39202542bf69de295/src/lanczos/lanczos.jl#L96-L102) where there is no license (Apache) copied.

Note that we do provide a link to a file, [resize.cpp](https://github.com/opencv/opencv/blob/de15636724967faf62c2d1bce26f4335e4b359e5/modules/imgproc/src/resize.cpp#L917-L946), that includes [a BSD 3-clause license](https://github.com/opencv/opencv/blob/de15636724967faf62c2d1bce26f4335e4b359e5/modules/imgproc/src/resize.cpp#L10-L40), not Apache, and that the link appears in the [documentation](http://juliamath.github.io/Interpolations.jl/latest/api/#Interpolations.Lanczos4OpenCV). You are right though that we should be more explicit.

**Comment by johnnychen94** [comment]
Let's move these to a new `src/imagemagick_compat.jl` file and copy its LICENSE at the beginning of it.

**Review by johnnychen94 — APPROVED** [review]

**Pull request merged**
