### PR TITLE
Error diffusion in XYZ color space

### LINKED ISSUE #59: Diffuse error in XYZ color space
The [ColorVectorSpace.jl readme](https://github.com/JuliaGraphics/ColorVectorSpace.jl#introduction) mentions: 
> Colorspaces such as RGB, unlike XYZ, are technically non-linear; perhaps the most "colorimetrically correct" approach when averaging two RGBs is to first convert each to XYZ, average them, and then convert back to RGB. 

This sounds to me like more accurate error diffusion would be possible in XYZ color space.

### PR DESCRIPTION
**Pull request by adrhill**
Closes #59

### CODE REVIEW

**Comment by adrhill** [comment]
Comparison to master:
| Color scheme | master | this PR |
|:--------------:|:-------:|:------:|
`:flag_us` | FloydSteinberg_flag_us | FloydSteinberg_flag_us
`:PuOr_6` |FloydSteinberg_PuOr_6 | FloydSteinberg_PuOr_6
`:websafe` |FloydSteinberg_websafe | FloydSteinberg_websafe
`:RdBu_10` | FloydSteinberg_RdBu_10 | FloydSteinberg_RdBu_10
`:jet` |FloydSteinberg_jet |  FloydSteinberg_jet
`:rainbow` |FloydSteinberg_rainbow | FloydSteinberg_rainbow

**Comment by adrhill** [comment]
Rerunning bechmarks.

**Comment by adrhill** [comment]
I'm not too sure what to make of the comparison. To me, XYZ looks "more colorful", maybe that's due to higher contrast.

**Comment by adrhill** [comment]
Not sure what's going on with the benchmarks. At least the relevant one is faster.

**Comment by adrhill** [comment]
@johnnychen94 any opinion on how to proceed with this one?

**Comment by johnnychen94** [comment]
> I'm not too sure what to make of the comparison. To me, XYZ looks "more colorful", maybe that's due to higher contrast.
Agree on this.

About the performance, we might need to figure out why it's slower for other unrelated cases. Let me run a local benchmark and see if it's more stable.

**Comment by johnnychen94** [comment]
Seems to be a benchmark noise introduced by GitHub Action (which is why we need an exclusive benchmark machine...)

<details>
<summary> This PR </summary>

# Benchmark Report for *C:\Users\jc\Documents\julia\DitherPunk.jl*

## Job Properties
* Time of benchmark: 12 Dec 2021 - 13:26
* Package commit: 67bd20
* Julia commit: 3bf9d1
* Julia command flags: None
* Environment variables: None

## Results
Below is a table of this job's results, obtained by running the benchmarks.
The values listed in the `ID` column have the structure `[parent_group, child_group, ..., key]`, and can be used to
index into the BaseBenchmarks suite to retrieve the corresponding benchmarks.
The percentages accompanying time and memory values in the below table are noise tolerances. The "true"
time/memory value for a given benchmark is expected to fall within this percentage of the reported value.
An empty cell means that the value was zero.

| ID                                               | time            | GC time  | memory          | allocations |
|--------------------------------------------------|----------------:|---------:|----------------:|------------:|
| `["closest color", "binary inplace"]`            |   3.671 μs (5%) |          |  64.11 KiB (1%) |           2 |
| `["closest color", "binary new"]`                |   2.087 μs (5%) |          |  64.11 KiB (1%) |           2 |
| `["closest color", "color inplace"]`             |  66.371 ms (5%) |          |  36.48 MiB (1%) |     2357848 |
| `["closest color", "color new"]`                 |  68.279 ms (5%) |          |  36.48 MiB (1%) |     2357848 |
| `["closest color", "per-channel inplace"]`       | 598.800 μs (5%) |          | 192.05 KiB (1%) |           2 |
| `["closest color", "per-channel new"]`           | 599.700 μs (5%) |          | 192.05 KiB (1%) |           2 |
| `["error diffusion", "binary inplace"]`          | 428.200 μs (5%) |          | 320.23 KiB (1%) |           5 |
| `["error diffusion", "binary new"]`              | 424.800 μs (5%) |          | 320.23 KiB (1%) |           5 |
| `["error diffusion", "color inplace"]`           |  57.132 ms (5%) |          |  16.01 MiB (1%) |      995660 |
| `["error diffusion", "color new"]`               |  54.063 ms (5%) |          |  16.01 MiB (1%) |      995660 |
| `["error diffusion", "per-channel inplace"]`     |   1.852 ms (5%) |          | 960.42 KiB (1%) |          11 |
| `["error diffusion", "per-channel new"]`         |   1.859 ms (5%) |          | 960.42 KiB (1%) |          11 |
| `["ordered dithering", "binary inplace"]`        |  45.600 μs (5%) |          |  69.42 KiB (1%) |           5 |
| `["ordered dithering", "binary new"]`            |  42.800 μs (5%) |          |  69.42 KiB (1%) |           5 |
| `["ordered dithering", "color inplace"]`         | 277.281 ms (5%) | 5.092 ms | 247.07 MiB (1%) |    14417965 |
| `["ordered dithering", "color new"]`             | 331.585 ms (5%) | 6.871 ms | 281.11 MiB (1%) |    16473466 |
| `["ordered dithering", "per-channel inplace"]`   | 633.200 μs (5%) |          | 207.98 KiB (1%) |          11 |
| `["ordered dithering", "per-channel new"]`       | 622.600 μs (5%) |          | 207.98 KiB (1%) |          11 |
| `["threshold dithering", "binary inplace"]`      |   6.600 μs (5%) |          | 128.27 KiB (1%) |           7 |
| `["threshold dithering", "binary new"]`          |   5.467 μs (5%) |          | 128.27 KiB (1%) |           7 |
| `["threshold dithering", "per-channel inplace"]` | 610.000 μs (5%) |          | 384.38 KiB (1%) |           8 |
| `["threshold dithering", "per-channel new"]`     | 599.800 μs (5%) |          | 384.38 KiB (1%) |           8 |

## Benchmark Group List
Here's a list of all the benchmark groups executed by this job:

- `["closest color"]`
- `["error diffusion"]`
- `["ordered dithering"]`
- `["threshold dithering"]`

## Julia versioninfo
```
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
      Microsoft Windows [Version 10.0.22000.318]
  CPU: 12th Gen Intel(R) Core(TM) i9-12900K: 
                 speed         user         nice          sys         idle          irq
       #1-24  3187 MHz   44330398            0     30136505    3005002960      2263816  ticks
       
  Memory: 31.79674530029297 GB (18474.96484375 MB free)
  Uptime: 128311.0 sec
  Load Avg:  0.0  0.0  0.0
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, goldmont)
```

</details>

<details>
<summary> master </summary>

# Benchmark Report for *C:\Users\jc\Documents\julia\DitherPunk.jl*

## Job Properties
* Time of benchmark: 12 Dec 2021 - 13:30
* Package commit: 2915ec
* Julia commit: 3bf9d1
* Julia command flags: None
* Environment variables: None

## Results
Below is a table of this job's results, obtained by running the benchmarks.
The values listed in the `ID` column have the structure `[parent_group, child_group, ..., key]`, and can be used to
index into the BaseBenchmarks suite to retrieve the corresponding benchmarks.
The percentages accompanying time and memory values in the below table are noise tolerances. The "true"
time/memory value for a given benchmark is expected to fall within this percentage of the reported value.
An empty cell means that the value was zero.

| ID                                               | time            | GC time  | memory          | allocations |
|--------------------------------------------------|----------------:|---------:|----------------:|------------:|
| `["closest color", "binary inplace"]`            |   3.457 μs (5%) |          |  64.11 KiB (1%) |           2 |
| `["closest color", "binary new"]`                |   1.988 μs (5%) |          |  64.11 KiB (1%) |           2 |
| `["closest color", "color inplace"]`             |  66.059 ms (5%) |          |  36.48 MiB (1%) |     2357848 |
| `["closest color", "color new"]`                 |  67.604 ms (5%) |          |  36.48 MiB (1%) |     2357848 |
| `["closest color", "per-channel inplace"]`       | 598.000 μs (5%) |          | 192.05 KiB (1%) |           2 |
| `["closest color", "per-channel new"]`           | 600.300 μs (5%) |          | 192.05 KiB (1%) |           2 |
| `["error diffusion", "binary inplace"]`          | 423.700 μs (5%) |          | 320.23 KiB (1%) |           5 |
| `["error diffusion", "binary new"]`              | 424.900 μs (5%) |          | 320.23 KiB (1%) |           5 |
| `["error diffusion", "color inplace"]`           |  68.161 ms (5%) |          |  31.87 MiB (1%) |     2035592 |
| `["error diffusion", "color new"]`               |  74.660 ms (5%) |          |  31.87 MiB (1%) |     2035592 |
| `["error diffusion", "per-channel inplace"]`     |   1.860 ms (5%) |          | 960.42 KiB (1%) |          11 |
| `["error diffusion", "per-channel new"]`         |   1.847 ms (5%) |          | 960.42 KiB (1%) |          11 |
| `["ordered dithering", "binary inplace"]`        |  45.300 μs (5%) |          |  69.42 KiB (1%) |           5 |
| `["ordered dithering", "binary new"]`            |  41.700 μs (5%) |          |  69.42 KiB (1%) |           5 |
| `["ordered dithering", "color inplace"]`         | 271.845 ms (5%) | 4.290 ms | 247.07 MiB (1%) |    14417965 |
| `["ordered dithering", "color new"]`             | 327.132 ms (5%) | 5.795 ms | 281.11 MiB (1%) |    16473466 |
| `["ordered dithering", "per-channel inplace"]`   | 620.900 μs (5%) |          | 207.98 KiB (1%) |          11 |
| `["ordered dithering", "per-channel new"]`       | 600.300 μs (5%) |          | 207.98 KiB (1%) |          11 |
| `["threshold dithering", "binary inplace"]`      |   7.000 μs (5%) |          | 128.27 KiB (1%) |           7 |
| `["threshold dithering", "binary new"]`          |   5.033 μs (5%) |          | 128.27 KiB (1%) |           7 |
| `["threshold dithering", "per-channel inplace"]` | 610.000 μs (5%) |          | 384.38 KiB (1%) |           8 |
| `["threshold dithering", "per-channel new"]`     | 600.100 μs (5%) |          | 384.38 KiB (1%) |           8 |

## Benchmark Group List
Here's a list of all the benchmark groups executed by this job:

- `["closest color"]`
- `["error diffusion"]`
- `["ordered dithering"]`
- `["threshold dithering"]`

## Julia versioninfo
```
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
      Microsoft Windows [Version 10.0.22000.318]
  CPU: 12th Gen Intel(R) Core(TM) i9-12900K: 
                 speed         user         nice          sys         idle          irq
       #1-24  3187 MHz   44479865            0     30182238    3010213412      2266302  ticks
       
  Memory: 31.79674530029297 GB (18551.83984375 MB free)
  Uptime: 128536.0 sec
  Load Avg:  0.0  0.0  0.0
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, goldmont)
```

</details>

**Review by johnnychen94 — APPROVED** [review]

**Comment by adrhill** [comment]
Sorry for stalling this over the holidays, I guess I'm just not sure what to make of the qualitative differences in the outputs. Is there some sort of metric for image similarity we could use? Alternatively, we could also just make the "diffusion color space" a parameter.

**Comment by johnnychen94** [comment]
> I guess I'm just not sure what to make of the qualitative differences in the outputs. Is there some sort of metric for image similarity we could use? Alternatively, we could also just make the "diffusion color space" a parameter.

Most people use PSNR and SSIM in image processing fields and they're implemented in https://github.com/JuliaImages/ImageQualityIndexes.jl. Compared to PSNR, SSIM gives more "visual" similarity results as it is designed based on human eyes model. There's also a multi-scale version of SSIM implemented there. I'm not sure if this satisfies your need.

**Comment by adrhill** [comment]
Thanks, I'll take a look at it!

**Comment by adrhill** [comment]
I made the color space a kwarg of all error diffusion methods, defaulting to `XYZ`. 

I also noticed a small issue where `clamp01` would be applied to `XYZ` colorants. As far as I can tell, the upper limits of `XYZ` are `(0.95047, 1.0, 1.08883)`. I replaced `clamp01` with a new function `clamp_limits` that dispatches on the color type.

**Pull request merged**
